#
# (C) Copyright 2008,2010-2014 STMicroelectronics.
# Sean McGoogan <Sean.McGoogan@st.com>
#
# See file CREDITS for list of people who contributed to this
# project.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of
# the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#

# ARCH-agnostic STMicroelectronics drivers
obj-$(CONFIG_STM_GLLCFF) += gllcff/
obj-$(CONFIG_SPI_FLASH) += common/spi_flash.o
obj-$(CONFIG_STM_ASC_SERIAL) += common/uart.o
obj-$(CONFIG_STM_SDHCI) += common/sdhci.o
obj-$(CONFIG_SYS_I2C) += common/i2c.o
