#
# (C) Copyright 2018 STMicroelectronics.
#
# See file CREDITS for list of people who contributed to this
# project.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation; either version 2 of
# the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#

obj-${CONFIG_STM_GLLCFF} += soc.o spacex_sysconf.o spacex_catson_boot.o catson_ibi.o
obj-${CONFIG_SPACEX_CATSON_MODEMLINK} += spacex_catson_modemlink.o spacex_catson_cdec_ethernet.o spacex_catson_panel_lookup.o
